config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :projects do
    member do
      post 'add_teammate'
      delete 'remove_teammate'
    end
    resources :tasks
  end

  root 'projects#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :teams
  has_many :users, through: :teams
  has_many :tasks
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user

  after_update :send_task_completed_notification, if: :saved_change_to_completed?

  private

  def send_task_completed_notification
    return unless completed

    TaskCompletedJob.perform_later(self)
  end
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :user_id, uniqueness: { scope: :project_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :teams
  has_many :projects, through: :teams
  has_many :tasks

  enum role: { default: 0, admin: 1 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show destroy add_teammate remove_teammate]
  before_action :find_user, only: %i[add_teammate remove_teammate]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show; end

  def create
    @project = current_user.projects.build(project_params)
    authorize @project

    if @project.save
      flash[:notice] = 'Project was successfully created.'
      redirect_to projects_path
    else
      render :new
    end
  end

  def destroy
    authorize @project

    @project.destroy
    flash[:notice] = 'Project was successfully destroyed.'
    redirect_to projects_path
  end

  def add_teammate
    authorize @project

    if @project.users << @user
      redirect_to project_path
    else
      flash[:notice] = 'User has already been taken'
    end
  end

  def remove_teammate
    authorize @project

    @project.users.delete(@user)
    redirect_to project_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_project, only: %i[index new create edit update destroy]
  before_action :set_task, only: %i[edit update destroy]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.new
  end

  def edit
    authorize @task
  end

  def create
    @task = @project.tasks.build(task_params.merge(user: current_user))
    authorize @task

    if @task.save
      TaskNotificationJob.perform_later(@task)
      flash[:notice] = 'Success result'
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Success result'
      redirect_to project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    authorize @task

    @task.destroy
    flash[:notice] = 'Successfully destroyed.'
    redirect_to project_tasks_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Project not found.'
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :end_day, :completed, :project_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_header.html.slim
header.bg-blue-100
  nav.mx-auto.flex.max-w-7xl.items-center.justify-between.p-6.lg:px-8[aria-label="Global"]
    .flex.lg:flex-1
      a.flex.-m-1.5.p-1.5 href=root_path
        img.h-10.w-auto[src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt=""]
    = render 'devise/shared/links'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Manager Task
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.15/tailwind.min.css", "inter-font"
    = stylesheet_link_tag "application"
    = javascript_importmap_tags
    = render 'layouts/header'
  body
    p.notice = notice
    p.alert = alert
    = yield

app/views/projects/_form.html.slim
= form_with(model: @project) do |form|

  .mt-4.sm:w-full.sm:max-w-sm
    = form.label :title, class: "block text-sm font-medium text-gray-900"
    = form.text_field :title, class: "w-full py-2 px-3 border rounded-md"

  .mt-4.sm:w-full.sm:max-w-sm
    = form.label :description, class: "block text-sm font-medium text-gray-900"
    = form.text_area :description, class: "w-full py-2 px-3 border rounded-md"

  .mt-4.sm:w-full.sm:max-w-sm
    = form.submit "Submit", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/projects/_form_add_team.html.slim
h3 Add Teammate
- if policy(@project).add_teammate?
  = form_with url: add_teammate_project_path(@project), method: :post, local: true do |form|
    = form.collection_select :user_id, User.all, :id, :email
    = form.submit 'Add to Team', class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/projects/index.html.slim
- if @projects.present?
  .relative.overflow-x-auto.shadow-md.sm:rounded-lg
    table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400
      thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
        tr
          th.px-6.py-3.text-lg Title
          th.px-6.py-3.text-lg Description
          th.px-6.py-3.text-lg Actions
      tbody
        - @projects.each do |project|
          tr.odd:bg-white.odd:dark:bg-gray-900.even:bg-gray-50.even:dark:bg-gray-800.border-b.dark:border-gray-700
            td.px-6.py-4.hover:underline.hover:text-black.text-base
              = link_to project.title, project_tasks_path(project)
            td.px-6.py-4.text-base= project.description
            td.px-6.py-4
              - if policy(@projects).destroy? 
                = button_to 'Destroy', project_path(project), method: :delete, class: 'font-medium text-red-600 dark:text-red-500 hover:underline'
- else
  - if policy(@projects).create? 
    = link_to 'New Project', new_project_path, class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'

app/views/projects/new.html.slim
div.p-4.max-w-xl.mx-auto.bg-white.rounded-xl.shadow-md
  h1.text-xl.font-semibold.text-gray-900 New Project
  = render 'form', project: @project
  = link_to raw('&#8592; Back'), projects_path, class: 'text-blue-600 dark:text-blue-500 hover:underline'

app/views/projects/show.html.slim
- if @project.users.present?
  .relative.overflow-x-auto.shadow-md.sm:rounded-lg
    table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400
      thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
        tr
          th.px-6.py-3.text-lg Teammate
      tbody
        - @project.users.each do |user|
          tr.odd:bg-white.odd:dark:bg-gray-900.even:bg-gray-50.even:dark:bg-gray-800.border-b.dark:border-gray-700
            td.px-6.py-4.text-base= user.email
            td.px-6.py-4
              - if policy(@project).remove_teammate?
                = button_to 'Remove', remove_teammate_project_path(@project, user_id: user.id), method: :delete, class: 'font-medium text-red-600 dark:text-red-500 hover:underline'
        = render 'form_add_team', project: @project
- else
  = render 'form_add_team', project: @project

app/views/tasks/_form.html.slim
= form_with(model: [@project, @task]) do |form|

  .mt-4.sm:w-full.sm:max-w-sm
    = form.label :title, class: "block text-sm font-medium text-gray-900"
    = form.text_field :title, class: "w-full py-2 px-3 border rounded-md"

  .mt-4.sm:w-full.sm:max-w-sm
    = form.label :description, class: "block text-sm font-medium text-gray-900"
    = form.text_area :description, class: "w-full py-2 px-3 border rounded-md"

  .mt-4.sm:w-full.sm:max-w-sm
    = form.label :end_day, class: "block text-sm font-medium text-gray-900"
    .mt-1.block.w-full.shadow-sm.sm:text-sm.border.border-gray-300.rounded-md
      = form.date_select :end_day, class: "w-full"

  .mt-4.sm:w-full.sm:max-w-sm
    = form.label :completed, class: "w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"
    = form.check_box :completed, class: 'flex items-center ps-4 border border-gray-200 rounded dark:border-gray-700'

  .mt-4.sm:w-full.sm:max-w-sm
    = form.submit "Submit", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/tasks/edit.html.slim
div.p-4.max-w-xl.mx-auto.bg-white.rounded-xl.shadow-md
  = turbo_frame_tag dom_id(@task, :title) do
    = render 'tasks/editing/edit_title', project: @project, task: @task

div.p-4.max-w-xl.mx-auto.bg-white.rounded-xl.shadow-md
  = turbo_frame_tag dom_id(@task, :description) do
    = render 'tasks/editing/edit_description', project: @project, task: @task

div.p-4.max-w-xl.mx-auto.bg-white.rounded-xl.shadow-md
  = turbo_frame_tag dom_id(@task, :end_day) do
    = render 'tasks/editing/edit_end_day', project: @project, task: @task

div.p-4.max-w-xl.mx-auto.bg-white.rounded-xl.shadow-md
  = turbo_frame_tag dom_id(@task, :completed) do
    = render 'tasks/editing/edit_completed', project: @project, task: @task

app/views/tasks/editing/_edit_completed.html.slim
= form_with(model: [@project, @task], local: true, data: { turbo_frame: dom_id(@task, :completed) }) do |form|
  = form.check_box :completed, class: 'flex items-center ps-4 border border-gray-200 rounded dark:border-gray-700'
  = form.submit "Done", class: "inline-flex items-center px-2 py-1 border border-transparent text-xs font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/tasks/editing/_edit_description.html.slim
= form_with(model: [@project, @task], local: true, data: { turbo_frame: dom_id(@task, :description) }) do |form|
  = form.text_area :description, value: task.title, class: "w-full py-2 px-3 border rounded-md"
  = form.submit "Save", class: "inline-flex items-center px-2 py-1 border border-transparent text-xs font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/tasks/editing/_edit_end_day.html.slim
= form_with(model: [@project, @task], local: true, data: { turbo_frame: dom_id(@task, :end_day) }) do |form|
  = form.date_select :end_day, value: task.end_day, class: "w-full py-2 px-3 border rounded-md"
  = form.submit "Save", class: "inline-flex items-center px-2 py-1 border border-transparent text-xs font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/tasks/editing/_edit_title.html.slim
= form_with(model: [@project, @task], local: true, data: { turbo_frame: dom_id(@task, :title) }) do |form|
  = form.text_field :title, value: task.title, class: "w-full py-2 px-3 border rounded-md"
  = form.submit "Save", class: "inline-flex items-center px-2 py-1 border border-transparent text-xs font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/tasks/index.html.slim
- if @project.present?
  .relative.overflow-x-auto.shadow-md.sm:rounded-lg
    table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400
      thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
        tr
          th.px-6.py-3.text-lg  Tasks
          th.px-6.py-3.text-lg  Descriptions
          th.px-6.py-3.text-lg  End Day
          th.px-6.py-3.text-lg  Completed
          th.px-6.py-3.text-lg  Editing
      tbody
        - @tasks.each do |task|
          tr.odd:bg-white.odd:dark:bg-gray-900.even:bg-gray-50.even:dark:bg-gray-800.border-b.dark:border-gray-700
            td.px-6.py-4.text-base
              = turbo_frame_tag dom_id(task, :title) do
                = task.title
            td.px-6.py-4.text-base
              = turbo_frame_tag dom_id(task, :description) do
                = task.description
            td.px-6.py-4.text-base
              = turbo_frame_tag dom_id(task, :end_day) do
                = task.end_day
            td.px-6.py-4.text-base
              = turbo_frame_tag dom_id(task, :completed) do
                = task.completed
            - if policy(task).edit?
              td.px-6.py-4
                = link_to 'Title', edit_project_task_path(@project, task), data: { turbo_frame: dom_id(task, :title) }, class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'
              td.px-6.py-4
                = link_to 'Description', edit_project_task_path(@project, task), data: { turbo_frame: dom_id(task, :description) }, class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'
              td.px-6.py-4
                = link_to 'Ending', edit_project_task_path(@project, task), data: { turbo_frame: dom_id(task, :end_day) }, class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'
              td.px-6.py-4
                = link_to 'Completed', edit_project_task_path(@project, task), data: { turbo_frame: dom_id(task, :completed) }, class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'
              td.px-6.py-4
                = button_to 'Destroy', [@project, task], method: :delete, class: 'font-medium text-red-600 dark:text-red-500 hover:underline'


  = link_to raw('&#8592; Back'), root_path
  = link_to 'New Task', new_project_task_path(@project), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'
- else
  = link_to 'New Task', new_project_task_path(@project), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'

app/views/tasks/new.html.slim
div.p-4.max-w-xl.mx-auto.bg-white.rounded-xl.shadow-md
  h1.text-xl.font-semibold.text-gray-900 New Task
  = render 'form', project: @project, task: @task
  = link_to raw('&#8592; Back'), project_tasks_path(@project), class: 'text-blue-600 dark:text-blue-500 hover:underline'